language: cpp
sudo: false

#addons:
#  # Ubuntu packages
#  apt:
#    packages:
#      # These are required by the Linux build
#      - libdb++-dev
#      - libboost-all-dev
#      - libqrencode-dev
#      - libminiupnpc-dev
#      - libminiupnpc8
#      # These are required by the Linux Qt build
#      - qt5-qmake
#      - libqt5-dev

install:
  # Travis already has OpenSSL and Boost installed via Homebrew, but we
  # need to add a couple more packages
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew upgrade ;
      brew install miniupnpc berkeley-db@4 ;
    fi

matrix:
  include:
  # Build Eidasd
  # Ubuntu 14.04 LTS (Trusty Tahr) is our latest (and only) Ubuntu version
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
          - libdb++-dev
          - libboost-all-dev
          - libqrencode-dev
          - libminiupnpc-dev
          - libminiupnpc8
    script: cd src && make -f makefile.unix -j2

  # Build Eidasd
  # Cross-compile Windows 32-bit daemon
  - os: linux
    dist: trusty
    sudo: required
    script: bash src/mxe-build.sh windows32

  # Build Eidasd
  # Cross-compile Windows 64-bit daemon
  - os: linux
    dist: trusty
    sudo: required
    script: bash src/mxe-build.sh windows64

  # Build Eidasd static
  # Ubuntu 14.04 LTS (Trusty Tahr) is our latest (and only) Ubuntu version
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
          - libdb++-dev
          - libboost-all-dev
          - libqrencode-dev
          - libminiupnpc-dev
          - libminiupnpc8
    script: cd src && make -f makefile.unix -j2 STATIC="all" LDFLAGS="-static"

  # Build Eidasd
  # Ubuntu 16.04 LTS (Xenial Xerus) not supported yet
  #- os: linux
  #  dist: xenial
  #  addons:
  #    apt:
  #      packages:
  #        - libdb++-dev
  #        - libboost-all-dev
  #        - libqrencode-dev
  #        - libminiupnpc-dev
  #        - libminiupnpc8
  #  script: cd src && make -f makefile.unix -j2

  # Build Eidasd
  # OS X 10.10 (Yosemite)
  - os: osx
    osx_image: xcode6.4
    script: cd src && make -f makefile.osx -j2

  # Build Eidasd static
  # OS X 10.10 (Yosemite)
  - os: osx
    osx_image: xcode6.4
    script: cd src && make -f makefile.osx -j2 STATIC="all" LDFLAGS="-static"

  # Build Eidasd
  # OS X 10.11 (El Capitan)
  - os: osx
    osx_image: xcode7.3
    script: cd src && make -f makefile.osx -j2

  # Build Eidasd static
  # OS X 10.11 (El Capitan)
  - os: osx
    osx_image: xcode7.3
    script: cd src && make -f makefile.osx -j2 STATIC="all" LDFLAGS="-static"

  # Build Eidasd
  # OS X 10.12 (Sierra)
  - os: osx
    osx_image: xcode8.3
    script: cd src && make -f makefile.osx -j2

  # Build Eidasd static
  # OS X 10.12 (Sierra)
  - os: osx
    osx_image: xcode8.3
    script: cd src && make -f makefile.osx -j2 STATIC="all" LDFLAGS="-static"

  # Build Eidasd
  # OS X 10.13 (High Sierra)
  - os: osx
    osx_image: xcode9.3beta
    script: cd src && make -f makefile.osx -j2

  # Build Eidasd static
  # OS X 10.13 (High Sierra)
  - os: osx
    osx_image: xcode9.3beta
    script: cd src && make -f makefile.osx -j2 STATIC="all" LDFLAGS="-static"

  # Build Eidas-qt
  # Ubuntu 14.04 LTS (Trusty Tahr) is our latest (and only) Ubuntu version
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
          - libdb++-dev
          - libboost-all-dev
          - libqrencode-dev
          - libminiupnpc-dev
          - libminiupnpc8
          - qt4-qmake
          - libqt4-dev
    script: qmake && make -j2

  # Build Eidas-qt
  # Ubuntu 16.04 LTS (Xenial Xerus) not supported yet
  #- os: linux
  #  dist: xenial
  #  addons:
  #    apt:
  #      packages:
  #        - libdb++-dev
  #        - libboost-all-dev
  #        - libqrencode-dev
  #        - libminiupnpc-dev
  #        - libminiupnpc8
  #        - qt4-qmake
  #        - libqt4-dev
  #  script: qmake && make -j2

  # Build Eidas-qt
  # Cross-compile Windows 32-bit GUI
  - os: linux
    dist: trusty
    sudo: required
    script: bash src/mxe-build.sh windows32-qt

  # Build Eidas-qt
  # Cross-compile Windows 64-bit GUI
  - os: linux
    dist: trusty
    sudo: required
    script: bash src/mxe-build.sh windows64-qt


  # Build Eidas-qt
  # OS X 10.10 (Yosemite)
  #  
  #   Error: You are using macOS 10.10.
  #   We (and Apple) do not provide support for this old version.
  #   You may encounter build failures or other breakages.
  #
  #- os: osx
  #  osx_image: xcode6.4
  #  script: brew install qrencode qt && ls /usr/local/opt/qt && /usr/local/opt/qt/bin/qmake && make -j2

  # Build Eidas-qt
  # OS X 10.11 (El Capitan)
  - os: osx
    osx_image: xcode7.3
    script: brew install qrencode qt && ls /usr/local/opt/qt && /usr/local/opt/qt/bin/qmake && make -j2

  # Build Eidas-qt
  # OS X 10.12 (Sierra)
  - os: osx
    osx_image: xcode8.3
    script: brew install qrencode qt && ls /usr/local/opt/qt && /usr/local/opt/qt/bin/qmake && make -j2

  # Build Eidas-qt
  # OS X 10.13 (High Sierra)
  - os: osx
    osx_image: xcode9.3beta
    script: brew install qrencode qt && ls /usr/local/opt/qt && /usr/local/opt/qt/bin/qmake && make -j2
